# Transformer hardware template: 16-core digital SRAM-CIM accelerator at 28 nm.
#
# Each core holds one 64x256 macro array (64 rows x 32 INT8 weight columns)
# with a storage-to-compute ratio of 8:1, a 16 KB input buffer and a 32 KB
# output buffer (256 bit/cycle). The cores share a 4 MB global buffer
# (512 bit/cycle) and 4 GB of DRAM (256 bit/cycle). Inputs and weights are INT8,
# partial sums 16 bit.
#
# SRAM access energies and leakage were computed once with CACTI 7.0 and are
# stored below, so this template does not need a CACTI build.

from __future__ import annotations

from Architecture.HardwareSpec import HardwareSpec


_TRANSFORMER_SPEC_DICT = {'cores': 16,
 'cycle_time_ns': None,
 'leakage_per_cycle_nJ': 0.4719655086538611,
 'macro': {'dimX': 64,
           'dimY': 32,
           'input_bit_per_cycle': 1,
           'precision': {'I': 8, 'W': 8, 'psum': 16, 'O_final': 8},
           'logic_energies_pJ': {'mult_1b': 0.0002835,
                                 'adder_1b': 0.003401999999999999,
                                 'reg_1b': 0.0017009999999999996},
           'tech_params': {'tech_node': 0.028,
                           'vdd': 0.9,
                           'nd2_cap': 0.0007,
                           'xor2_cap': 0.0010499999999999997,
                           'dff_cap': 0.0020999999999999994,
                           'nd2_area': 6.14e-07,
                           'xor2_area': 1.4736e-06,
                           'dff_area': 3.6840000000000002e-06,
                           'nd2_dly': 0.0478,
                           'xor2_dly': 0.11472},
           'spatial_axes': [{'name': 'cores',
                             'size': 16,
                             'allowed_loops': ['P', 'Q', 'K', 'G'],
                             'source_memory_per_operand': {'I': 'Global_buffer',
                                                           'W': 'Global_buffer',
                                                           'O': 'Global_buffer'}},
                            {'name': 'dimX',
                             'size': 64,
                             'allowed_loops': ['R', 'S', 'C'],
                             'source_memory_per_operand': {'I': 'Input_buffer',
                                                           'W': 'Global_buffer',
                                                           'O': 'OReg'}},
                            {'name': 'dimY',
                             'size': 32,
                             'allowed_loops': ['K'],
                             'source_memory_per_operand': {'I': 'IReg',
                                                           'W': 'Global_buffer',
                                                           'O': 'Output_buffer'}}],
           'compartment_depth': 8,
           'weight_double_buffer': False},
 'memory_hierarchy': [{'name': 'Dram',
                       'size_bits': 34359738368,
                       'replication': 'shared_all_cores',
                       'r_bw_bits_per_cycle': 256,
                       'w_bw_bits_per_cycle': 256,
                       'r_cost_per_bit_pJ': 7.91,
                       'w_cost_per_bit_pJ': 7.91,
                       'operands': ['I', 'W', 'O'],
                       'served_dimensions_zigzag': 'all',
                       'area_mm2': 0.0,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': 4,
                       'min_w_granularity_bits': 4},
                      {'name': 'Global_buffer',
                       'size_bits': 33554432,
                       'replication': 'shared_all_cores',
                       'r_bw_bits_per_cycle': 512,
                       'w_bw_bits_per_cycle': 512,
                       'r_cost_per_bit_pJ': 0.4182283125,
                       'w_cost_per_bit_pJ': 0.2767365,
                       'operands': ['I', 'W', 'O'],
                       'served_dimensions_zigzag': 'all',
                       'area_mm2': 0.8022823,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': 8,
                       'min_w_granularity_bits': 8},
                      {'name': 'Output_buffer',
                       'size_bits': 262144,
                       'replication': 'per_core',
                       'r_bw_bits_per_cycle': 256,
                       'w_bw_bits_per_cycle': 256,
                       'r_cost_per_bit_pJ': 0.03950850937500001,
                       'w_cost_per_bit_pJ': 0.04694506875,
                       'operands': ['O'],
                       'served_dimensions_zigzag': [[0, 1, 0], [1, 0, 0]],
                       'area_mm2': 0.0068512,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': 8,
                       'min_w_granularity_bits': 8},
                      {'name': 'Input_buffer',
                       'size_bits': 131072,
                       'replication': 'per_core',
                       'r_bw_bits_per_cycle': 256,
                       'w_bw_bits_per_cycle': 256,
                       'r_cost_per_bit_pJ': 0.029533106250000007,
                       'w_cost_per_bit_pJ': 0.032814871875,
                       'operands': ['I'],
                       'served_dimensions_zigzag': [[0, 1, 0], [1, 0, 0]],
                       'area_mm2': 0.0068512,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': 8,
                       'min_w_granularity_bits': 8},
                      {'name': 'OReg',
                       'size_bits': 16,
                       'replication': 'per_core',
                       'r_bw_bits_per_cycle': 16,
                       'w_bw_bits_per_cycle': 16,
                       'r_cost_per_bit_pJ': 0.0,
                       'w_cost_per_bit_pJ': 0.0017009999999999996,
                       'operands': ['O'],
                       'served_dimensions_zigzag': [[0, 1, 0]],
                       'area_mm2': 5.8944000000000003e-05,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': None,
                       'min_w_granularity_bits': None},
                      {'name': 'IReg',
                       'size_bits': 8,
                       'replication': 'per_core',
                       'r_bw_bits_per_cycle': 8,
                       'w_bw_bits_per_cycle': 8,
                       'r_cost_per_bit_pJ': 0.0,
                       'w_cost_per_bit_pJ': 0.0017009999999999996,
                       'operands': ['I'],
                       'served_dimensions_zigzag': [[1, 0, 0]],
                       'area_mm2': 2.9472000000000002e-05,
                       'r_latency_cycles': 1,
                       'w_latency_cycles': 1,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': None,
                       'min_w_granularity_bits': None},
                      {'name': 'Macro',
                       'size_bits': 64,
                       'replication': 'per_core',
                       'r_bw_bits_per_cycle': 8,
                       'w_bw_bits_per_cycle': 8,
                       'r_cost_per_bit_pJ': 0.0,
                       'w_cost_per_bit_pJ': 0.02575,
                       'operands': ['W'],
                       'served_dimensions_zigzag': [],
                       'area_mm2': 0.0,
                       'r_latency_cycles': 0,
                       'w_latency_cycles': 0,
                       'ports': {'r': 0, 'w': 0, 'rw': 1},
                       'min_r_granularity_bits': None,
                       'min_w_granularity_bits': None}],
 'metadata': {'tech_node': '28nm',
              'imc_family': 'digital_SRAM_IMC',
              'notes': 'CIM_ACC_DEFAULT_SETUP_TRANSFORMER (2026-05-13): 16-core digital SRAM CIM, '
                       '28nm, I=W=8b psum=16b, 64x32 macro, 4 MB GBuf, 16 KB IBuf / 32 KB OBuf per '
                       'core, 4 GB DRAM @256 bit/cyc. Only OBuf differs from '
                       'CIM_ACC_TEMPLATE_TRANSFORMER (16→32 KB per core, 1:2 ratio matching 8b/16b '
                       'width asymmetry).'}}


def default_spec() -> HardwareSpec:
    return HardwareSpec.from_dict(_TRANSFORMER_SPEC_DICT)
